  /* ===================== ÇOKTAN SEÇMELİ TESTLER ===================== */

  var Q6 = {
    mat:[
      {u:"TEMA 1 · Çarpanlar, Katlar, Asal Sayılar", q:"84 sayısının asal çarpanlarına ayrılmış hâli hangisidir?", o:["2² · 3 · 7","2 · 3² · 7","2² · 21","2³ · 3 · 7"], a:0,
       w:"84 = 2 · 42 = 2 · 2 · 21 = 2² · 3 · 7."},
      {u:"TEMA 1 · Çarpanlar, Katlar, Asal Sayılar", q:"24 cm ve 36 cm'lik iki kurdele hiç artmadan eşit ve en uzun parçalara bölünecek. Bir parça kaç cm olur?", o:["6","8","12","18"], a:2,
       w:"\"En uzun eşit parça\" EBOB'u gerektirir: EBOB(24, 36) = 12 cm."},
      {u:"TEMA 1 · Çarpanlar, Katlar, Asal Sayılar", q:"4 320 sayısı aşağıdakilerden hangisine kalansız bölünmez?", o:["3","5","7","9"], a:2,
       w:"Rakamlar toplamı 9 olduğu için 3 ve 9'a, son rakamı 0 olduğu için 5'e bölünür. 7'ye bölünmez."},
      {u:"TEMA 2 · İstatistiksel Araştırma Süreci", q:"7, 3, 9, 3, 5, 8 verilerinin ortancası kaçtır?", o:["5","6","7","3"], a:1,
       w:"Sıralı: 3, 3, 5, 7, 8, 9. Veri sayısı çift → ortanca (5+7)÷2 = 6."},
      {u:"TEMA 3 · Kesirler, Ondalık Gösterim, Uzunluk", q:"5/6 ÷ 2/3 işleminin sonucu kaçtır?", o:["5/9","5/4","10/18","3/4"], a:1,
       w:"İkinci kesir ters çevrilip çarpılır: 5/6 · 3/2 = 15/12 = 5/4."},
      {u:"TEMA 3 · Kesirler, Ondalık Gösterim, Uzunluk", q:"2,349 sayısı yüzde birler basamağına yuvarlanırsa kaç olur?", o:["2,34","2,35","2,3","2,4"], a:1,
       w:"Binde birler basamağındaki 9 ≥ 5 olduğu için yüzde birler 1 artar: 2,35."},
      {u:"TEMA 4 · Veriden Olasılığa", q:"Bir zar atıldığında çift sayı gelme olasılığı kaçtır?", o:["1/6","1/3","1/2","2/3"], a:2,
       w:"Çift sayılar 2, 4, 6 → 3/6 = 1/2."},
      {u:"TEMA 5 · Açılar, Üçgenler, Dörtgenler", q:"Bir üçgenin iki iç açısı 45° ve 65° ise üçüncü açı kaç derecedir?", o:["60°","70°","80°","110°"], a:1,
       w:"Üçgende iç açılar toplamı 180°: 180 − (45+65) = 70°."},
      {u:"TEMA 5 · Açılar, Üçgenler, Dörtgenler", q:"Bir paralelkenarın bir açısı 70° ise ona komşu açı kaç derecedir?", o:["70°","90°","110°","140°"], a:2,
       w:"Paralelkenarda ardışık (komşu) açılar bütünlerdir: 180 − 70 = 110°."},
      {u:"TEMA 6 · İşlemlerle Cebirsel Düşünme", q:"2, 5, 8, 11, … örüntüsünün kuralı hangisidir?", o:["3n","3n − 1","3n + 1","2n + 1"], a:1,
       w:"Fark 3, ilk terim 2 → 3n − 1. Kontrol: n=1 için 2, n=2 için 5."},
      {u:"TEMA 7 · Alan, Çember, Merkez Açı", q:"Tabanı 10 cm, yüksekliği 6 cm olan üçgenin alanı kaç cm²'dir?", o:["16","30","60","120"], a:1,
       w:"Üçgen alanı = (taban × yükseklik) ÷ 2 = (10 × 6) ÷ 2 = 30 cm²."},
      {u:"TEMA 7 · Alan, Çember, Merkez Açı", q:"Yarıçapı 7 cm olan çemberin uzunluğu kaç cm'dir? (π = 3)", o:["21","42","49","147"], a:1,
       w:"Çember uzunluğu = 2 · π · r = 2 · 3 · 7 = 42 cm."}
    ],
    fen:[
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Güneş sistemindeki en büyük gezegen hangisidir?", o:["Satürn","Dünya","Jüpiter","Neptün"], a:2,
       w:"Jüpiter en büyük gezegendir; Merkür ise en küçüğüdür."},
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Gezegenler büyükten küçüğe sıralandığında üçüncü sırada hangisi yer alır?", o:["Neptün","Uranüs","Dünya","Satürn"], a:1,
       w:"Sıralama: Jüpiter, Satürn, Uranüs, Neptün, Dünya, Venüs, Mars, Merkür. Uranüs üçüncüdür."},
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Uranüs ile Neptün karşılaştırıldığında aşağıdakilerden hangisi doğrudur?", o:["Uranüs hem daha büyük hem daha ağırdır","Neptün hem daha büyük hem daha ağırdır","Uranüs daha büyük, Neptün daha ağırdır","Neptün daha büyük, Uranüs daha ağırdır"], a:2,
       w:"Uranüs'ün çapı daha geniştir ama Neptün daha yoğun olduğu için kütlece daha ağırdır."},
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Güneş'e en yakın gezegen olan Merkür, büyüklük sıralamasında kaçıncıdır?", o:["1.","4.","7.","8."], a:3,
       w:"Merkür hem Güneş'e en yakın hem de en küçük gezegendir; büyüklükte sonuncudur."},
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Güneş tutulması sırasında gök cisimlerinin sıralaması nasıldır?", o:["Güneş – Dünya – Ay","Güneş – Ay – Dünya","Ay – Güneş – Dünya","Dünya – Güneş – Ay"], a:1,
       w:"Ay, Dünya ile Güneş'in arasına girer. Yeni Ay evresinde ve gündüz gerçekleşir."},
      {u:"ÜNİTE 2 · Kuvvetin Etkisinde Hareket", q:"Bir cisme zıt yönde 30 N ve 18 N'luk kuvvetler uygulanıyor. Bileşke kuvvet kaç N'dur?", o:["12 N","18 N","48 N","540 N"], a:0,
       w:"Zıt yönlü kuvvetler çıkarılır: 30 − 18 = 12 N, 30 N'luk kuvvetin yönünde."},
      {u:"ÜNİTE 2 · Kuvvetin Etkisinde Hareket", q:"180 km yolu 3 saatte alan bir aracın sürati kaç km/h'dir?", o:["45","60","90","540"], a:1,
       w:"Sürat = yol ÷ süre = 180 ÷ 3 = 60 km/h."},
      {u:"ÜNİTE 3 · Canlılarda Sistemler", q:"Besinlerin kana emildiği organ hangisidir?", o:["Mide","İnce bağırsak","Kalın bağırsak","Yemek borusu"], a:1,
       w:"Emilim ince bağırsakta, villus denen parmaksı çıkıntılarla olur."},
      {u:"ÜNİTE 3 · Canlılarda Sistemler", q:"Kanın pıhtılaşmasını sağlayan yapı hangisidir?", o:["Alyuvar","Akyuvar","Kan pulcuğu","Plazma"], a:2,
       w:"Kan pulcukları (trombositler) pıhtılaşmayı sağlar."},
      {u:"ÜNİTE 4 · Işığın Yansıması ve Renkler", q:"Yansıma kanununda açılar hangi doğruya göre ölçülür?", o:["Yüzeye","Normale","Gelen ışına","Yansıyan ışına"], a:1,
       w:"Gelme açısı = yansıma açısı; ikisi de yüzeye dik olan normal doğrusuna göre ölçülür."},
      {u:"ÜNİTE 4 · Işığın Yansıması ve Renkler", q:"Yeşil bir yaprağı yeşil görmemizin sebebi nedir?", o:["Yeşili soğurması","Yeşili yansıtması","Yeşil ışık üretmesi","Bütün renkleri yansıtması"], a:1,
       w:"Cisim hangi rengi yansıtıyorsa o renkte görünür; yaprak yeşili yansıtır, diğerlerini soğurur."},
      {u:"ÜNİTE 5 · Maddenin Ayırt Edici Özellikleri", q:"Kütlesi 240 g, hacmi 30 cm³ olan cismin yoğunluğu kaç g/cm³'tür?", o:["6","8","7200","0,125"], a:1,
       w:"d = m ÷ V = 240 ÷ 30 = 8 g/cm³."},
      {u:"ÜNİTE 5 · Maddenin Ayırt Edici Özellikleri", q:"Aynı maddeden yapılmış 10 g ve 100 g'lık iki parçanın erime noktaları için ne söylenebilir?", o:["100 g'lıkki daha yüksektir","10 g'lıkki daha yüksektir","Eşittir","Karşılaştırılamaz"], a:2,
       w:"Erime noktası ayırt edici özelliktir, madde miktarına bağlı değildir. Miktar arttıkça yalnızca erime süresi uzar."},
      {u:"ÜNİTE 6 · Elektriğin İletimi ve Direnç", q:"Aynı maddeden yapılmış, aynı uzunluktaki iki telden kalın olanın direnci nasıldır?", o:["Daha büyüktür","Daha küçüktür","Eşittir","Sıfırdır"], a:1,
       w:"Kesit (kalınlık) arttıkça akıma açılan yol genişler, direnç azalır."},
      {u:"ÜNİTE 7 · Sürdürülebilir Yaşam ve Etkileşim", q:"Aşağıdakilerden hangisi biyoçeşitliliği tehdit eden bir etmen DEĞİLDİR?", o:["Kaçak avlanma","Ağaçlandırma","Habitat yok edilmesi","Orman yangınları"], a:1,
       w:"Ağaçlandırma biyoçeşitliliği korur; diğerleri tehdit eder."}
    ],
    tur:[
      {u:"KONU 1 · Sözcükte Anlam", q:"\"Masanın ayağı kırıldı.\" cümlesinde \"ayak\" hangi anlamdadır?", o:["Gerçek anlam","Yan anlam","Mecaz anlam","Terim anlam"], a:1,
       w:"İnsan ayağına benzediği için masanın destek kısmına da ayak denmiş — yan anlam."},
      {u:"KONU 1 · Sözcükte Anlam", q:"Aşağıdakilerden hangisi eş sesli (sesteş) sözcüktür?", o:["Siyah","Yüz","Uzun","Mektep"], a:1,
       w:"\"Yüz\" hem sayı, hem surat, hem de yüzmek anlamındadır."},
      {u:"KONU 2 · Deyimler, Atasözleri ve Söz Sanatları", q:"\"Ağaç yaşken eğilir.\" ifadesi nedir?", o:["Deyim","Atasözü","Söz sanatı","Terim"], a:1,
       w:"Öğüt verdiği ve tek başına bir yargı olduğu için atasözüdür."},
      {u:"KONU 2 · Deyimler, Atasözleri ve Söz Sanatları", q:"\"Rüzgâr pencereyi dövüyordu.\" cümlesinde hangi söz sanatı vardır?", o:["Benzetme","Abartma","Kişileştirme","Konuşturma"], a:2,
       w:"Rüzgâra insana ait \"dövmek\" eylemi verilmiş — kişileştirme."},
      {u:"KONU 3 · Cümlede Anlam", q:"\"Sınavı kazanmak için çok çalıştı.\" cümlesindeki anlam ilişkisi nedir?", o:["Neden – sonuç","Amaç – sonuç","Koşul","Karşılaştırma"], a:1,
       w:"Eylem, ileride olmasını istediği bir hedef uğruna yapılmış — amaç-sonuç."},
      {u:"KONU 4 · Paragraf ve Metin Türleri", q:"Hayvanların konuşturulduğu, sonunda ders veren kısa öykülere ne ad verilir?", o:["Masal","Fabl","Anı","Deneme"], a:1,
       w:"Fabl, hayvanların konuşturulduğu ve ders veren kısa öyküdür."},
      {u:"KONU 5 · Sözcük Yapısı", q:"\"Kitaplar\" sözcüğünün yapısı nedir?", o:["Basit","Türemiş","Birleşik","Bileşik"], a:0,
       w:"Aldığı \"-lar\" çoğul ekidir, yani çekim ekidir; yeni sözcük türetmediği için sözcük basittir."},
      {u:"KONU 6 · İsim, Sıfat ve Zamir", q:"\"Üç öğrenci geldi, ikisi geç kalmıştı.\" cümlesinde \"ikisi\" nedir?", o:["Sayı sıfatı","Belgisiz zamir","İşaret sıfatı","Kişi zamiri"], a:1,
       w:"İsmin yerini tuttuğu için zamirdir; miktarı belirsiz bıraktığı için belgisiz zamirdir."},
      {u:"KONU 7 · Fiiller: Kip ve Kişi", q:"\"Okumalısın\" fiilinin kipi hangisidir?", o:["İstek","Şart","Gereklilik","Emir"], a:2,
       w:"-malı / -meli eki gereklilik kipidir."},
      {u:"KONU 7 · Fiiller: Kip ve Kişi", q:"\"Ödevini yazmış.\" cümlesi konuşan kişi hakkında ne söyler?", o:["Olaya tanık olmuştur","Olayı başkasından duymuştur","Olay henüz olmamıştır","Olay her zaman olur"], a:1,
       w:"-miş duyulan geçmiş zaman ekidir; konuşan olaya tanık olmamış, duymuştur."},
      {u:"KONU 8 · Yazım Kuralları ve Noktalama", q:"Aşağıdaki cümlelerin hangisinde yazım yanlışı vardır?", o:["Ben de geleceğim.","Evde kimse yok.","Herkez bahçeye çıktı.","Her şey yolunda."], a:2,
       w:"Doğru yazımı \"herkes\"tir."},
      {u:"KONU 8 · Yazım Kuralları ve Noktalama", q:"\"Ankara'ya gittim.\" cümlesinde kesme işareti neden kullanılmıştır?", o:["Özel ada gelen yapım eki için","Özel ada gelen çekim eki için","Cümle uzun olduğu için","Vurgu yapmak için"], a:1,
       w:"Özel adlara gelen çekim ekleri kesmeyle ayrılır; yapım ekleri ayrılmaz."}
    ],
    sos:[
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Çocuk Hakları Sözleşmesi hangi yılda kabul edilmiştir?", o:["1945","1969","1989","2000"], a:2,
       w:"Birleşmiş Milletler tarafından 1989'da kabul edilmiştir."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Aşağıdakilerden hangisi \"ben dili\"ne örnektir?", o:["Sen hep geç kalıyorsun.","Beklerken kaygılanıyorum.","Ben senin yüzünden geciktim.","Hiç düşünmüyorsun."], a:1,
       w:"Ben dili suçlamaz, kişinin kendi duygusunu anlatır."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Türkiye hangi yarım kürelerde yer alır?", o:["Kuzey ve Batı","Güney ve Doğu","Kuzey ve Doğu","Güney ve Batı"], a:2,
       w:"36°–42° kuzey enlemleri, 26°–45° doğu boylamları arasındadır."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Her mevsim yağışlı olmasıyla bilinen iklim hangisidir?", o:["Akdeniz","Karadeniz","Karasal","Çöl"], a:1,
       w:"Karadeniz ikliminin en belirgin özelliği her mevsim yağışlı olmasıdır."},
      {u:"ALAN 3 · Ortak Mirasımız", q:"Türk adının geçtiği ilk Türkçe yazılı belge hangisidir?", o:["Kutadgu Bilig","Orhun Yazıtları","Divânu Lugâti't-Türk","Divan-ı Hikmet"], a:1,
       w:"8. yüzyılda dikilen Orhun (Göktürk) Yazıtları'dır."},
      {u:"ALAN 3 · Ortak Mirasımız", q:"Malazgirt Savaşı'nın (1071) en önemli sonucu nedir?", o:["Büyük Selçuklu kuruldu","Anadolu'nun kapıları Türklere açıldı","İstanbul fethedildi","Kâğıt Çin dışına yayıldı"], a:1,
       w:"1071'de Alparslan Bizans'ı yendi ve Anadolu'nun Türkleşmesi başladı."},
      {u:"ALAN 4 · Yaşayan Demokrasimiz", q:"Ülkemizde kanun yapma (yasama) yetkisi kime aittir?", o:["Cumhurbaşkanı","TBMM","Mahkemeler","Valilikler"], a:1,
       w:"Yasama yetkisi Türkiye Büyük Millet Meclisi'ne aittir."},
      {u:"ALAN 4 · Yaşayan Demokrasimiz", q:"Yönetme yetkisinin tek kişide ve genellikle veraset yoluyla bulunduğu yönetim şekli hangisidir?", o:["Demokrasi","Cumhuriyet","Monarşi","Oligarşi"], a:2,
       w:"Monarşide yetki tek kişidedir ve çoğunlukla babadan oğula geçer."},
      {u:"ALAN 5 · Hayatımızdaki Ekonomi", q:"Aşağıdakilerden hangisi sermayeye örnektir?", o:["Orman","Eğitimli mühendis","Fabrika binası","Kömür yatağı"], a:2,
       w:"Sermaye; makine, bina, araç ve para gibi üretimde kullanılan varlıklardır."},
      {u:"ALAN 5 · Hayatımızdaki Ekonomi", q:"Arızalı ürün alan tüketici, satıcıdan sonuç alamazsa nereye başvurur?", o:["Tüketici Hakem Heyeti","Valilik","Belediye","Muhtarlık"], a:0,
       w:"Önce satıcıya, çözüm alamazsa Tüketici Hakem Heyeti'ne başvurulur."},
      {u:"ALAN 6 · Teknoloji ve Sosyal Bilimler", q:"Geçmiş toplumları kalıntı ve buluntularından inceleyen bilim dalı hangisidir?", o:["Tarih","Arkeoloji","Sosyoloji","Antropoloji"], a:1,
       w:"Arkeoloji kalıntı ve buluntularla, tarih ise yazılı belgelerle çalışır."},
      {u:"ALAN 6 · Teknoloji ve Sosyal Bilimler", q:"Bir yazarın kitabını izinsiz çoğaltıp satmak hangi hakkın ihlalidir?", o:["Seçme hakkı","Telif hakkı","Dilekçe hakkı","Eğitim hakkı"], a:1,
       w:"Telif hakkı, eseri üretenin eseri üzerindeki hakkını korur."}
    ],
    ing:[
      {u:"TEMA 2 · Classroom Life & Learning", q:"There ____ twenty desks in our classroom.", o:["is","are","has","have"], a:1,
       w:"\"Desks\" çoğul olduğu için \"are\" kullanılır."},
      {u:"TEMA 2 · Classroom Life & Learning", q:"\"Kapıyı açma.\" cümlesinin İngilizce karşılığı hangisidir?", o:["Not open the door.","Don't open the door.","You don't open the door.","No open the door."], a:1,
       w:"Olumsuz emir cümlesi \"Don't + yalın fiil\" ile kurulur."},
      {u:"TEMA 1 · School Life & Education", q:"We have Maths ____ Tuesday.", o:["at","in","on","to"], a:2,
       w:"Gün adlarından önce \"on\" kullanılır."},
      {u:"TEMA 3 · Personal Life & Well-Being", q:"She ____ TV in the evening. (olumsuz)", o:["doesn't watches","don't watch","doesn't watch","isn't watch"], a:2,
       w:"3. tekil kişide \"doesn't\" kullanılır ve fiil yalın kalır."},
      {u:"TEMA 3 · Personal Life & Well-Being", q:"Sözcükleri doğru sıraya koy: am / never / I / late", o:["I never am late.","Never I am late.","I am never late.","Am I never late."], a:2,
       w:"Sıklık zarfları \"be\" fiilinden sonra gelir."},
      {u:"TEMA 4 · Family Life & Home", q:"My sister ____ got long curly hair.", o:["have","has","is","are"], a:1,
       w:"3. tekil kişi (she) ile \"has got\" kullanılır."},
      {u:"TEMA 5 · Life in the Neighbourhood, City & Social Life", q:"The bank is ____ the hospital and the school.", o:["next to","between","opposite","behind"], a:1,
       w:"İki şeyin arasında olmak \"between\" ile anlatılır."},
      {u:"TEMA 6 · Life in the World & Culture", q:"İstanbul is ____ than Ankara.", o:["big","more big","bigger","the biggest"], a:2,
       w:"Kısa sıfatta karşılaştırma için -er eklenir ve \"than\" gelir."},
      {u:"TEMA 7 · Life in Nature & Global Problems", q:"We ____ waste water.", o:["should","shouldn't","must","can"], a:1,
       w:"Yapılmaması gereken bir davranış için \"shouldn't\" uygundur."},
      {u:"TEMA 8 · Life in the Universe & Future", q:"People ____ on other planets one day.", o:["live","will live","lived","are living"], a:1,
       w:"Gelecekle ilgili tahmin için \"will + yalın fiil\" kullanılır."}
    ],
    din:[
      {u:"ÜNİTE 1 · Peygamber ve İlahi Kitap İnancı", q:"Hz. Musa'ya indirilen ilahi kitap hangisidir?", o:["Zebur","Tevrat","İncil","Kur'an"], a:1,
       w:"Tevrat Hz. Musa'ya, Zebur Hz. Davud'a, İncil Hz. İsa'ya indirilmiştir."},
      {u:"ÜNİTE 1 · Peygamber ve İlahi Kitap İnancı", q:"\"Emanet\" sıfatı ne anlama gelir?", o:["Doğru sözlü olmak","Güvenilir olmak","Akıllı olmak","Günah işlememek"], a:1,
       w:"Emanet, peygamberin güvenilir olması demektir."},
      {u:"ÜNİTE 2 · Ramazan ve Oruç", q:"Orucun başlama vaktine ne ad verilir?", o:["Sahur","İmsak","İftar","Teravih"], a:1,
       w:"İmsak orucun başlama, iftar bitiş vaktidir. Sahur imsaktan önce yenen yemektir."},
      {u:"ÜNİTE 2 · Ramazan ve Oruç", q:"Bir daha oruç tutamayacak durumdaki yaşlı bir kişi ne yapar?", o:["Kaza eder","Fidye verir","Fitre verir","Hiçbir şey yapmaz"], a:1,
       w:"Kaza sonradan tutabilecek kişi içindir; bir daha tutamayacak kişi fidye verir."},
      {u:"ÜNİTE 3 · Ahlaki Davranışlar", q:"Bir kişide olmayan bir kusuru varmış gibi söylemeye ne ad verilir?", o:["Gıybet","İftira","Kibir","Haset"], a:1,
       w:"Gıybet var olan kusuru arkadan konuşmak, iftira olmayan kusuru uydurmaktır."},
      {u:"ÜNİTE 4 · Peygamberliğinden Önce Hz. Muhammed", q:"Hz. Muhammed hangi yıl ve nerede doğmuştur?", o:["571 – Medine","571 – Mekke","610 – Mekke","622 – Medine"], a:1,
       w:"571 yılında Mekke'de doğmuş, hicretten sonra Medine'de vefat etmiştir."},
      {u:"ÜNİTE 4 · Peygamberliğinden Önce Hz. Muhammed", q:"Mekke'de haksızlığa uğrayanların hakkını korumak için kurulan topluluğun adı nedir?", o:["Ahilik","Hılfu'l-Fudûl","Darü'l-Erkam","Dârülaceze"], a:1,
       w:"Hılfu'l-Fudûl (Erdemliler Birliği), Hz. Muhammed'in de katıldığı topluluktur."},
      {u:"ÜNİTE 5 · Kültürümüzdeki Dinî Motifler", q:"Su üzerine boya damlatılarak yapılan desenlerin kâğıda aktarıldığı sanat hangisidir?", o:["Hat","Tezhip","Ebru","Çini"], a:2,
       w:"Ebru su üzerinde yapılan desen sanatıdır; hat güzel yazı, tezhip süsleme sanatıdır."}
    ]
  };

  var Q7 = {
    mat:[
      {u:"TEMA 1 · Tam Sayılar", q:"(−8) + 5 işleminin sonucu kaçtır?", o:["−13","−3","3","13"], a:1,
       w:"İşaretler farklı: büyük mutlak değerden küçüğü çıkarılır (8 − 5 = 3), büyüğün işareti yazılır → −3."},
      {u:"TEMA 1 · Tam Sayılar", q:"(−7) − (−12) işleminin sonucu kaçtır?", o:["−19","−5","5","19"], a:2,
       w:"Çıkanın işareti değişir: −7 + 12 = 5."},
      {u:"TEMA 1 · Tam Sayılar", q:"(−3) · 6 işleminin sonucu kaçtır?", o:["−18","−9","9","18"], a:0,
       w:"Farklı işaretli iki sayının çarpımı negatiftir: −18."},
      {u:"TEMA 1 · Tam Sayılar", q:"(−36) ÷ (−9) işleminin sonucu kaçtır?", o:["−4","4","−27","27"], a:1,
       w:"Aynı işaretli iki sayının bölümü pozitiftir: 4."},
      {u:"TEMA 1 · Tam Sayılar", q:"|−11| + |4| işleminin sonucu kaçtır?", o:["−15","−7","7","15"], a:3,
       w:"Mutlak değer uzaklıktır, negatif olmaz: 11 + 4 = 15."},
      {u:"TEMA 1 · Tam Sayılar", q:"Aşağıdaki sıralamalardan hangisi doğrudur?", o:["−2 < −9 < 0","−9 < −2 < 0","0 < −2 < −9","−2 < 0 < −9"], a:1,
       w:"Sayı doğrusunda solda kalan küçüktür: −9 < −2 < 0."},
      {u:"TEMA 1 · Tam Sayılar", q:"(−5) · (−2) · (−1) işleminin sonucu kaçtır?", o:["−10","10","−7","7"], a:0,
       w:"Çarpımda üç tane negatif var; negatif adedi tek olduğu için sonuç negatiftir: −10."},
      {u:"TEMA 1 · Tam Sayılar", q:"Hava sıcaklığı −6 °C iken 9 derece düşerse kaç °C olur?", o:["3","−3","−15","15"], a:2,
       w:"Düşme çıkarmadır: −6 − 9 = −15 °C."},
      {u:"TEMA 1 · Tam Sayılar", q:"|−3 + 7| işleminin sonucu kaçtır?", o:["4","10","−4","−10"], a:0,
       w:"Mutlak değerin içi önce hesaplanır: |4| = 4. Soru |−3| + |7| olsaydı sonuç 10 olurdu."},
      {u:"TEMA 1 · Tam Sayılar", q:"Bir asansör 3. kattayken 7 kat aşağı iniyor. Hangi kattadır?", o:["−4","4","−10","10"], a:0,
       w:"3 − 7 = −4, yani 4. bodrum katı."},
      {u:"TEMA 1 · Sayılar ve Nicelikler (1)", q:"−3/4 ile −2/3 sayılarından hangisi büyüktür?", o:["−3/4","−2/3","Eşittirler","Karşılaştırılamaz"], a:1,
       w:"Paydalar eşitlenince −9/12 ve −8/12 olur. Sayı doğrusunda sağdaki büyüktür: −2/3."},
      {u:"TEMA 1 · Sayılar ve Nicelikler (1)", q:"0,666… devirli ondalık sayısının kesir gösterimi hangisidir?", o:["6/10","2/3","3/5","6/99"], a:1,
       w:"Devreden tek basamak varsa payda 9 olur: 6/9 = 2/3."},
      {u:"TEMA 1 · Sayılar ve Nicelikler (1)", q:"|−7| + |3| işleminin sonucu kaçtır?", o:["−4","4","10","−10"], a:2,
       w:"Mutlak değer uzaklıktır, hep pozitiftir: 7 + 3 = 10."},
      {u:"TEMA 2 · Sayılar ve Nicelikler (2)", q:"200 TL'lik bir ürüne önce %20, sonra %10 indirim yapılıyor. Son fiyat kaç TL'dir?", o:["140","144","146","150"], a:1,
       w:"200 × 0,80 = 160; 160 × 0,90 = 144. İkinci indirim yeni fiyat üzerinden hesaplanır."},
      {u:"TEMA 2 · Sayılar ve Nicelikler (2)", q:"4 işçi bir işi 12 günde bitiriyorsa, 6 işçi aynı işi kaç günde bitirir?", o:["8","10","16","18"], a:0,
       w:"İşçi ile süre ters orantılıdır: 4 × 12 = 6 × x, x = 8 gün."},
      {u:"TEMA 3 · İşlemlerle Cebirsel Düşünme", q:"3x − 5 = 16 denkleminde x kaçtır?", o:["5","7","9","11"], a:1,
       w:"İki tarafa 5 eklenir: 3x = 21, sonra 3'e bölünür: x = 7."},
      {u:"TEMA 3 · İşlemlerle Cebirsel Düşünme", q:"−2x > 8 eşitsizliğinin çözümü hangisidir?", o:["x > −4","x < −4","x > 4","x < 4"], a:1,
       w:"Negatif sayıyla bölünce eşitsizliğin yönü değişir: x < −4."},
      {u:"TEMA 4 · Dönüşüm", q:"A(3, 2) noktasının y eksenine göre yansıma görüntüsü hangisidir?", o:["(3, −2)","(−3, 2)","(−3, −2)","(2, 3)"], a:1,
       w:"y eksenine göre yansımada x koordinatı işaret değiştirir."},
      {u:"TEMA 6 · Geometrik Nicelikler (2)", q:"Ayrıtları 2, 3 ve 4 cm olan dikdörtgenler prizmasının hacmi kaç cm³'tür?", o:["9","24","52","26"], a:1,
       w:"Hacim = a × b × c = 2 × 3 × 4 = 24 cm³."},
      {u:"TEMA 5 · Geometrik Nicelikler (1)", q:"Aynı prizmanın (2, 3, 4 cm) yüzey alanı kaç cm²'dir?", o:["24","36","52","104"], a:2,
       w:"2(ab + bc + ac) = 2(6 + 12 + 8) = 52 cm²."},
      {u:"TEMA 7 · Geometrik Şekiller", q:"Bir üçgenin iki kenarı 5 cm ve 9 cm ise üçüncü kenar hangisi OLAMAZ?", o:["5 cm","7 cm","13 cm","4 cm"], a:3,
       w:"Üçüncü kenar 4 ile 14 arasında olmalı. 4 cm bu aralığın dışındadır."},
      {u:"TEMA 8 · İstatistiksel Araştırma Süreci", q:"2, 4, 6, 8 verilerinin ortalama mutlak sapması kaçtır?", o:["2","3","4","5"], a:0,
       w:"Ortalama 5. Farklar 3, 1, 1, 3 → (3+1+1+3) ÷ 4 = 2."},
      {u:"TEMA 9 · Veriden Olasılığa", q:"Bir zar atıldığında 3'ten büyük gelme olasılığı kaçtır?", o:["1/6","1/3","1/2","2/3"], a:2,
       w:"4, 5, 6 istenen durumlardır: 3/6 = 1/2."}
    ],
    fen:[
      {u:"ÜNİTE 1 · Uzay Çağı", q:"Işık yılı neyin birimidir?", o:["Zaman","Uzaklık","Hız","Kütle"], a:1,
       w:"Işığın bir yılda aldığı YOL'dur, yani bir uzaklık birimidir."},
      {u:"ÜNİTE 1 · Uzay Çağı", q:"Aşağıdakilerden hangisi kendi ışığını üretir?", o:["Ay","Dünya","Güneş","Mars"], a:2,
       w:"Güneş bir yıldızdır; yıldızlar ışık üretir, gezegenler yansıtır."},
      {u:"ÜNİTE 2 · Kuvvet ve Enerjiyi Keşfedelim", q:"50 N'luk kuvvetle bir cisim kuvvet yönünde 4 m taşınırsa yapılan iş kaç joule'dür?", o:["12,5","54","200","2000"], a:2,
       w:"İş = Kuvvet × Yol = 50 × 4 = 200 J."},
      {u:"ÜNİTE 2 · Kuvvet ve Enerjiyi Keşfedelim", q:"Bir kişi duvarı itiyor ama duvar yerinden oynamıyor. Yapılan iş kaçtır?", o:["Sıfır","Kuvvet kadar","Belirsiz","Kütle kadar"], a:0,
       w:"Yol alınmadığı için iş sıfırdır. Yorulmak fizikte iş yapmak anlamına gelmez."},
      {u:"ÜNİTE 3 · Vücudumuzdaki Sistemler", q:"Karbonhidratların kimyasal sindirimi nerede başlar?", o:["Mide","Ağız","İnce bağırsak","Kalın bağırsak"], a:1,
       w:"Ağızdaki tükürük enzimi nişastayı parçalamaya başlar."},
      {u:"ÜNİTE 3 · Vücudumuzdaki Sistemler", q:"Küçük kan dolaşımı kalp ile hangi organ arasında gerçekleşir?", o:["Böbrek","Karaciğer","Akciğer","Beyin"], a:2,
       w:"Küçük dolaşım kalp–akciğer arasındadır ve kanın temizlendiği dolaşımdır."},
      {u:"ÜNİTE 4 · Işığın Kırılması ve Mercekler", q:"Miyop göz kusuru hangi mercekle düzeltilir?", o:["İnce kenarlı","Kalın kenarlı","Düz ayna","Çukur ayna"], a:1,
       w:"Miyopta görüntü retinanın önünde oluşur; ışığı dağıtan kalın kenarlı mercek gerekir."},
      {u:"ÜNİTE 5 · Maddenin Doğasına Yolculuk", q:"Atomun çekirdeğinde hangi tanecikler bulunur?", o:["Yalnız proton","Proton ve elektron","Proton ve nötron","Yalnız elektron"], a:2,
       w:"Elektronlar çekirdeğin etrafındaki katmanlarda döner."},
      {u:"ÜNİTE 5 · Maddenin Doğasına Yolculuk", q:"Alkol-su karışımı hangi yöntemle ayrılır?", o:["Süzme","Eleme","Damıtma","Mıknatısla ayırma"], a:2,
       w:"Alkol suda çözündüğü için süzme işe yaramaz; kaynama noktası farkından yararlanılır."},
      {u:"ÜNİTE 6 · Elektriklenme", q:"Birbirini iten iki cismin yükleri için ne söylenebilir?", o:["Aynı cinstir","Zıt cinstir","Biri nötrdür","İkisi de nötrdür"], a:0,
       w:"Aynı cins yükler birbirini iter, zıt cins yükler çeker."},
      {u:"ÜNİTE 6 · Elektriklenme", q:"Etkiyle elektriklenmede cismin net yükü nasıl değişir?", o:["Artar","Azalır","Değişmez","Sıfırlanır"], a:2,
       w:"Yükler yalnızca cismin içinde ayrışır; dışarıdan yük alışverişi olmaz."},
      {u:"ÜNİTE 7 · Sürdürülebilir Yaşam ve Enerji", q:"Aşağıdakilerden hangisi yenilenemez enerji kaynağıdır?", o:["Rüzgâr","Doğal gaz","Jeotermal","Hidroelektrik"], a:1,
       w:"Doğal gaz bir fosil yakıttır; tükendiğinde kısa sürede yenilenmez."}
    ],
    tur:[
      {u:"TEMA 1 · Hayat Boyu Gelişim", q:"\"Okula gidiyorum.\" cümlesindeki fiilin kipi hangisidir?", o:["Görülen geçmiş","Şimdiki zaman","Geniş zaman","Gelecek zaman"], a:1,
       w:"-yor eki şimdiki zaman kipidir."},
      {u:"TEMA 1 · Hayat Boyu Gelişim", q:"\"Bu ödevi bitirmeliyim.\" cümlesindeki kip hangisidir?", o:["İstek","Şart","Gereklilik","Emir"], a:2,
       w:"-meli / -malı eki gereklilik kipidir."},
      {u:"TEMA 1 · Hayat Boyu Gelişim", q:"Hangi cümlede anlam (zaman) kayması vardır?", o:["Dün sinemaya gittik.","Yarın İstanbul'a gidiyorum.","Her sabah erken kalkarım.","Şu an ders çalışıyorum."], a:1,
       w:"Şimdiki zaman eki kullanılmış ama cümle \"yarın\" ile gelecek zamanı anlatıyor."},
      {u:"TEMA 2 · Bir Hilal Uğruna", q:"\"Ben de bir zamanlar öğrenciydim.\" sözcüğündeki ek fiilin çekimi nedir?", o:["Görülen geçmiş zaman","Duyulan geçmiş zaman","Şart","Geniş zaman"], a:0,
       w:"İsim soylu \"öğrenci\" sözcüğüne gelen -di, ek fiilin görülen geçmiş zaman çekimidir."},
      {u:"TEMA 3 · İletişim ve Sosyal İlişkiler", q:"\"Çocuk hızlı koştu.\" cümlesinde \"hızlı\" sözcüğü nedir?", o:["Sıfat","Durum zarfı","Zaman zarfı","İsim"], a:1,
       w:"\"Koştu\" fiilini nitelediği için durum zarfıdır."},
      {u:"TEMA 3 · İletişim ve Sosyal İlişkiler", q:"\"Çok güzel bir gündü.\" cümlesinde \"çok\" sözcüğü hangisini niteler?", o:["gün","güzel","bir","gündü"], a:1,
       w:"\"Çok\", sıfat olan \"güzel\"i niteleyen miktar zarfıdır."},
      {u:"TEMA 4 · Türk Sanatı", q:"\"Ağaçlar bize el sallıyordu.\" cümlesinde hangi söz sanatı vardır?", o:["Benzetme","Abartma","Kişileştirme","Karşıtlık"], a:2,
       w:"İnsan dışı bir varlığa insan davranışı verildiği için kişileştirmedir."},
      {u:"TEMA 4 · Türk Sanatı", q:"\"Aslanım benim!\" ifadesinde hangi söz sanatı vardır?", o:["Güzel benzetme","Kişileştirme","Abartma","Konuşturma"], a:0,
       w:"Benzetme yönü ve edatı düşmüş, yalnızca kendisine benzetilen kalmıştır."},
      {u:"TEMA 5 · Okuma Kültürü", q:"\"En ideal çözüm buydu.\" cümlesindeki bozukluğun nedeni nedir?", o:["Özne eksikliği","Gereksiz sözcük kullanımı","Tamlama yanlışı","Mantık hatası"], a:1,
       w:"\"İdeal\" zaten en iyi demektir; başına \"en\" getirmek gereksizdir."},
      {u:"TEMA 5 · Okuma Kültürü", q:"\"Kitabı okudu ve kütüphaneye verdi.\" cümlesinde ne eksiktir?", o:["Özne","Nesne","Yüklem","Zarf"], a:1,
       w:"İkinci yüklemin nesnesi eksiktir: \"…ve onu kütüphaneye verdi.\""},
      {u:"TEMA 3 · İletişim ve Sosyal İlişkiler", q:"Aşağıdakilerden hangisi nesnel bir yargıdır?", o:["Bu film çok sıkıcıydı.","Türkiye'nin başkenti Ankara'dır.","En güzel mevsim sonbahardır.","Bence o haklıydı."], a:1,
       w:"Nesnel yargı kanıtlanabilir ve kişiden kişiye değişmez."},
      {u:"TEMA 5 · Okuma Kültürü", q:"Aşağıdaki cümlelerin hangisinde yazım yanlışı vardır?", o:["Herkes sınava girdi.","Yalnız başına geldi.","Yanlış cevap verdi.","Herkez bahçeye çıktı."], a:3,
       w:"Doğru yazımı \"herkes\"tir."}
    ],
    sos:[
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Aşağıdakilerden hangisi \"ben dili\" kullanımına örnektir?", o:["Sen hep geç kalıyorsun.","Sesin yükselince üzülüyorum.","Senin yüzünden geç kaldık.","Hiç anlamıyorsun beni."], a:1,
       w:"Ben dili suçlamaz, konuşanın kendi duygusunu anlatır."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Empati ile sempati arasındaki fark nedir?", o:["Empatide taraf olunur","Sempatide aynı duygu paylaşılır","İkisi aynıdır","Empati yalnızca yazıda olur"], a:1,
       w:"Empati karşıdakinin yerinden bakmaktır; sempatide ona taraf olunur ve aynı duygu paylaşılır."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Türkiye'de nüfusun kıyı bölgelerde yoğunlaşmasının temel nedeni nedir?", o:["Yer altı kaynakları","Elverişli iklim ve ekonomik faaliyetler","Yüksek rakım","Orman örtüsü"], a:1,
       w:"Ilıman iklim, tarım, sanayi, ulaşım ve turizm imkânları kıyılara nüfus çeker."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Nitelikli iş gücünün yurt dışına gitmesine ne ad verilir?", o:["İç göç","Mevsimlik göç","Beyin göçü","Zorunlu göç"], a:2,
       w:"Beyin göçü, eğitimli ve nitelikli insanların başka ülkeye yerleşmesidir."},
      {u:"ALAN 3 · Ortak Mirasımız", q:"İstanbul'un fethi (1453) hangi yüzyılda gerçekleşmiştir?", o:["14. yüzyıl","15. yüzyıl","16. yüzyıl","13. yüzyıl"], a:1,
       w:"Yüzyıl hesabında ilk iki basamağa 1 eklenir: 14 + 1 = 15. yüzyıl."},
      {u:"ALAN 3 · Ortak Mirasımız", q:"Ahilik teşkilatının temel amacı nedir?", o:["Orduyu eğitmek","Esnaf ve sanatkârın mesleki-ahlaki düzenini sağlamak","Vergi toplamak","Sınır güvenliğini korumak"], a:1,
       w:"Ahilik, üretimde kalite ve ahlak standardı kuran bir esnaf teşkilatıdır."},
      {u:"ALAN 4 · Yaşayan Demokrasimiz", q:"Ülkemizde yasama görevi kime aittir?", o:["Cumhurbaşkanı","TBMM","Bağımsız mahkemeler","Valilikler"], a:1,
       w:"Kanun yapma yetkisi Türkiye Büyük Millet Meclisi'ne aittir."},
      {u:"ALAN 4 · Yaşayan Demokrasimiz", q:"Kuvvetler ayrılığı ilkesi neden gereklidir?", o:["Devlet küçülsün diye","Yetkinin kötüye kullanılmasını önlemek için","Vergi artsın diye","Seçim yapılmasın diye"], a:1,
       w:"Üç yetki tek elde toplanırsa denetim kalkar; ayrılması yetkinin kötüye kullanılmasını önler."},
      {u:"ALAN 5 · Hayatımızdaki Ekonomi", q:"Bilinçli bir tüketici aşağıdakilerden hangisini yapar?", o:["Etiketi okumadan alır","Fiş ve garanti belgesini saklar","Sadece reklamlara güvenir","Fiyat karşılaştırması yapmaz"], a:1,
       w:"Fiş ve garanti belgesi, tüketici haklarını kullanabilmenin ön şartıdır."},
      {u:"ALAN 5 · Hayatımızdaki Ekonomi", q:"Aşağıdakilerden hangisi bir tüketici hakkı DEĞİLDİR?", o:["Bilgi edinme hakkı","Güvenlik hakkı","Tazmin hakkı","Vergi vermeme hakkı"], a:3,
       w:"Vergi vermek bir yükümlülüktür, tüketici hakkı değildir."},
      {u:"ALAN 6 · Teknoloji ve Sosyal Bilimler", q:"Telif hakkı neyi korur?", o:["Devletin sınırlarını","Eseri üreten kişinin haklarını","Ürünün fiyatını","Tüketicinin adresini"], a:1,
       w:"Telif hakkı, bir eseri ortaya koyan kişinin emeğini ve haklarını korur."},
      {u:"ALAN 6 · Teknoloji ve Sosyal Bilimler", q:"Siber zorbalıkla karşılaşan biri öncelikle ne yapmalıdır?", o:["Aynı şekilde karşılık vermeli","Hesabını kapatıp unutmalı","Kanıtı kaydedip bir yetişkine bildirmeli","Tartışmayı sürdürmeli"], a:2,
       w:"Yanıt vermeden ekran görüntüsü alınmalı ve bir yetişkine ya da öğretmene bildirilmelidir."}
    ],
    ing:[
      {u:"TEMA 1 · School Life & Education", q:"We ____ wear a uniform at our school. (okulun kuralı)", o:["must","have to","mustn't","don't have to"], a:1,
       w:"Dışarıdan gelen bir kural için \"have to\" kullanılır."},
      {u:"TEMA 1 · School Life & Education", q:"\"Cumartesi okula gelmek zorunda değiliz.\" cümlesinin karşılığı hangisidir?", o:["We mustn't come to school on Saturday.","We don't have to come to school on Saturday.","We can't come to school on Saturday.","We shouldn't come to school on Saturday."], a:1,
       w:"\"mustn't\" yasak, \"don't have to\" gerek yok demektir."},
      {u:"TEMA 2 · Classroom Life & Learning", q:"Cümleyi tamamla: I ____ swim when I was five.", o:["can","could","will can","am able"], a:1,
       w:"Geçmişteki yetenek için \"could\" kullanılır."},
      {u:"TEMA 2 · Classroom Life & Learning", q:"Hangisi doğrudur?", o:["I will can finish it.","I will be able to finish it.","I will could finish it.","I can will finish it."], a:1,
       w:"\"can\" gelecek zamanla birlikte kullanılamaz; yerine \"be able to\" gelir."},
      {u:"TEMA 3 · Personal Life & Well-Being", q:"You look tired. You ____ go to bed early.", o:["should","shouldn't","must not","don't have to"], a:0,
       w:"Tavsiye için \"should\" kullanılır ve ardından yalın fiil gelir."},
      {u:"TEMA 4 · Family Life & Home", q:"He ____ to the cinema yesterday. (olumsuz)", o:["didn't went","doesn't go","didn't go","not went"], a:2,
       w:"\"did\" zamanı taşır, fiil yalın kalır: didn't go."},
      {u:"TEMA 4 · Family Life & Home", q:"\"Eskiden Ankara'da otururduk.\" cümlesinin karşılığı hangisidir?", o:["We use to live in Ankara.","We used to live in Ankara.","We are used to live in Ankara.","We used to living in Ankara."], a:1,
       w:"Geçmişte düzenli yapılan ama artık yapılmayan şeyler için \"used to + yalın fiil\"."},
      {u:"TEMA 5 · Life in the Neighbourhood, City & Social Life", q:"Bir daveti kibarca reddeden ifade hangisidir?", o:["No.","I don't want to.","I'd love to, but I'm afraid I can't.","Maybe."], a:2,
       w:"İngilizcede kibar ret, teşekkür ve gerekçe içerir."},
      {u:"TEMA 6 · Life in the World & Culture", q:"The Blue Mosque is one of ____ landmarks in İstanbul.", o:["famous","more famous","the most famous","most famous"], a:2,
       w:"Üstünlük derecesinde uzun sıfatla \"the most\" kullanılır."},
      {u:"TEMA 7 · Life in Nature & Global Problems", q:"If it ____ tomorrow, we will not go out.", o:["will rain","rains","rained","is raining"], a:1,
       w:"Type 1 koşul cümlesinde \"if\"li kısımda \"will\" kullanılmaz, present simple gelir."},
      {u:"TEMA 7 · Life in Nature & Global Problems", q:"\"Nesli tükenmekte olan tür\" ifadesinin İngilizcesi hangisidir?", o:["extinct animal","endangered species","wild habitat","rare nature"], a:1,
       w:"\"Endangered species\" nesli tehlike altındaki tür demektir."},
      {u:"TEMA 8 · Life in the Universe & Future", q:"I have already decided — I ____ study medicine.", o:["will","am going to","might","would"], a:1,
       w:"Karar önceden verildiyse \"be going to\" kullanılır."}
    ],
    din:[
      {u:"ÜNİTE 1 · Melek ve Ahiret İnancı", q:"Melekler hangi özelliğe sahiptir?", o:["Topraktan yaratılmışlardır","Nurdan yaratılmışlardır","Ateşten yaratılmışlardır","Sudan yaratılmışlardır"], a:1,
       w:"Melekler nurdan yaratılmış, gözle görülmeyen varlıklardır."},
      {u:"ÜNİTE 1 · Melek ve Ahiret İnancı", q:"Kabirde soru sormakla görevli melekler hangileridir?", o:["Cebrail ve Mikail","Kirâmen Kâtibîn","Münker ve Nekir","İsrafil ve Azrail"], a:2,
       w:"Kirâmen Kâtibîn yaptıklarımızı yazar; Münker ve Nekir kabirde soru sorar."},
      {u:"ÜNİTE 2 · Hac, Umre ve Kurban", q:"Hac ile umre arasındaki en belirgin fark nedir?", o:["Umrenin belirli bir zamanı yoktur","Umre farzdır","Hac Mekke dışında yapılır","Umrede ihrama girilmez"], a:0,
       w:"Hac yılın belirli günlerinde yapılır; umre yılın her zamanı yapılabilir."},
      {u:"ÜNİTE 2 · Hac, Umre ve Kurban", q:"Aşağıdakilerden hangisi haccın farzlarından biri DEĞİLDİR?", o:["İhram","Arafat vakfesi","Ziyaret tavafı","Kurban kesmek"], a:3,
       w:"Haccın üç farzı ihram, Arafat vakfesi ve ziyaret tavafıdır."},
      {u:"ÜNİTE 3 · İslam Düşüncesinde Yorumlar", q:"Aşağıdakilerden hangisi fıkhi bir yorumdur?", o:["Maturidilik","Eşarilik","Hanefilik","Mevlevilik"], a:2,
       w:"Hanefilik fıkhi, Maturidilik ve Eşarilik itikadi, Mevlevilik tasavvufi yorumdur."},
      {u:"ÜNİTE 4 · Peygamber Olarak Hz. Muhammed", q:"Hz. Muhammed'e peygamberlikten önce verilen \"güvenilir\" anlamındaki sıfat nedir?", o:["el-Emin","el-Hakim","es-Sadık","el-Halim"], a:0,
       w:"Mekkeliler ona dürüstlüğü ve güvenilirliği nedeniyle \"el-Emin\" derdi."},
      {u:"ÜNİTE 4 · Peygamber Olarak Hz. Muhammed", q:"\"Tebliğ\" sıfatı ne anlama gelir?", o:["Doğru sözlü olmak","Aldığı mesajı eksiksiz iletmek","Günah işlememek","Akıllı olmak"], a:1,
       w:"Tebliğ, peygamberin aldığı vahyi eksiksiz iletmesidir."},
      {u:"ÜNİTE 5 · Yaşayan Dünya Dinleri", q:"Aşağıdakilerden hangisi ilahi din DEĞİLDİR?", o:["Yahudilik","Hıristiyanlık","İslam","Budizm"], a:3,
       w:"Budizm vahye ve tek tanrı inancına dayanmadığı için ilahi din sayılmaz."}
    ]
  };
