  /* ===================== YANLIŞ SORU HAVUZU =====================
     Bu sorular ANA TESTE GİRMEZ. Yalnızca "Yanlışlarım" modunda,
     çocuğun yanlış yaptığı ünitelerden taze soru olarak servis edilir.
     Böylece aynı soruyu ezberlemek yerine aynı konuyu farklı soruyla
     tekrar çözer.

     Yapı ana testle aynı; u alanı ünite başlığıyla birebir eşleşmeli.
     Hedef: aktif her ünite için 5 havuz sorusu. */

  var H6 = {
    mat:[
      {u:"TEMA 1 · Çarpanlar, Katlar, Asal Sayılar", q:"48 sayısının asal çarpanlarına ayrılmış hâli hangisidir?", o:["2⁴ · 3","2³ · 6","2² · 12","2⁵ · 3"], a:0,
       w:"48 = 2·24 = 2·2·12 = 2·2·2·6 = 2·2·2·2·3 = 2⁴ · 3."},
      {u:"TEMA 1 · Çarpanlar, Katlar, Asal Sayılar", q:"1 ile 30 arasında kaç tane asal sayı vardır?", o:["8","9","10","11"], a:2,
       w:"2, 3, 5, 7, 11, 13, 17, 19, 23, 29 → 10 tane."},
      {u:"TEMA 1 · Çarpanlar, Katlar, Asal Sayılar", q:"30 ve 45 sayılarının EBOB'u kaçtır?", o:["5","10","15","90"], a:2,
       w:"30 = 2·3·5, 45 = 3²·5. Ortak çarpanların en küçük üslüleri: 3·5 = 15."},
      {u:"TEMA 1 · Çarpanlar, Katlar, Asal Sayılar", q:"2 736 sayısı 4 ile kalansız bölünür mü?", o:["Evet, son iki basamağı 4'ün katı","Hayır, tek sayıdır","Evet, rakamlar toplamı 4'ün katı","Hayır, 4 ile bitmiyor"], a:0,
       w:"Son iki basamak 36'dır ve 36 = 4·9 olduğundan sayı 4'e bölünür."},
      {u:"TEMA 1 · Çarpanlar, Katlar, Asal Sayılar", q:"Boyu 40 cm, eni 24 cm olan dikdörtgen kâğıt, artmayacak şekilde eşit ve en büyük karelere bölünecek. Bir karenin kenarı kaç cm olur?", o:["4","6","8","12"], a:2,
       w:"EBOB(40, 24) = 8 → kenar 8 cm."},
      {u:"TEMA 2 · İstatistiksel Araştırma Süreci", q:"5, 9, 9, 12, 15 verilerinin tepe değeri kaçtır?", o:["5","9","10","15"], a:1,
       w:"En çok tekrar eden değer 9'dur."},
      {u:"TEMA 2 · İstatistiksel Araştırma Süreci", q:"Bir sınıfta 4 öğrenci 70, 6 öğrenci 90 almıştır. Sınıf ortalaması kaçtır?", o:["78","80","82","85"], a:2,
       w:"(4·70 + 6·90) ÷ 10 = (280 + 540) ÷ 10 = 82."},
      {u:"TEMA 2 · İstatistiksel Araştırma Süreci", q:"Daire grafiğinde toplam kaç derecedir?", o:["90°","180°","270°","360°"], a:3,
       w:"Daire grafiği tüm veriyi 360°'lik bir daire olarak gösterir."},
      {u:"TEMA 2 · İstatistiksel Araştırma Süreci", q:"İstatistiksel araştırmanın ilk adımı hangisidir?", o:["Veriyi toplamak","Araştırma sorusunu kurmak","Grafik çizmek","Yorumlamak"], a:1,
       w:"Önce ne araştırılacağı belirlenir; veri ondan sonra toplanır."},
      {u:"TEMA 2 · İstatistiksel Araştırma Süreci", q:"3, 5, 8, 8, 21 verilerinde ortalama ile ortanca karşılaştırıldığında ne söylenir?", o:["Ortalama daha büyüktür","Ortanca daha büyüktür","Eşittirler","Karşılaştırılamaz"], a:0,
       w:"Ortalama 9, ortanca 8'dir. 21 uç değeri ortalamayı yukarı çeker."}
    ],
    fen:[
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Güneş sistemindeki en küçük gezegen hangisidir?", o:["Merkür","Mars","Venüs","Dünya"], a:0,
       w:"Merkür hem Güneş'e en yakın hem de en küçük gezegendir."},
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Dış (gaz) gezegenlerin ortak özelliği hangisidir?", o:["Küçük ve kayaçtırlar","Büyük ve gazdan oluşurlar","Uyduları yoktur","Güneş'e çok yakındırlar"], a:1,
       w:"Jüpiter, Satürn, Uranüs ve Neptün dev ve gaz yapılıdır; halka ve çok sayıda uyduları vardır."},
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Ay tutulmasında gök cisimlerinin sıralaması hangisidir?", o:["Güneş – Ay – Dünya","Güneş – Dünya – Ay","Ay – Dünya – Güneş","Dünya – Güneş – Ay"], a:1,
       w:"Dünya, Güneş ile Ay'ın arasına girer ve gölgesi Ay'ın üzerine düşer."},
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Bir gezegenin çevresinde dolanan gök cismine ne ad verilir?", o:["Yıldız","Uydu","Asteroit","Meteor"], a:1,
       w:"Ay, Dünya'nın uydusudur."},
      {u:"ÜNİTE 1 · Güneş Sistemi ve Tutulmalar", q:"Venüs'ün Merkür'den daha sıcak olmasının sebebi nedir?", o:["Güneş'e daha yakın olması","Yoğun atmosferinin ısıyı hapsetmesi","Daha büyük olması","Daha hızlı dönmesi"], a:1,
       w:"Sera etkisi nedeniyle ısı uzaya kaçamaz; Venüs en sıcak gezegendir."},
      {u:"ÜNİTE 2 · Kuvvetin Etkisinde Hareket", q:"Zıt yönlü 45 N ve 20 N'luk kuvvetlerin bileşkesi kaç N'dur?", o:["25","32,5","65","900"], a:0,
       w:"Zıt yönlü kuvvetler çıkarılır: 45 − 20 = 25 N, büyük kuvvetin yönünde."},
      {u:"ÜNİTE 2 · Kuvvetin Etkisinde Hareket", q:"240 m yolu 30 saniyede alan bir koşucunun sürati kaç m/s'dir?", o:["6","8","10","12"], a:1,
       w:"Sürat = 240 ÷ 30 = 8 m/s."},
      {u:"ÜNİTE 2 · Kuvvetin Etkisinde Hareket", q:"72 km/h süratle giden araç 2 saatte kaç km yol alır?", o:["36","72","144","216"], a:2,
       w:"Yol = sürat × süre = 72 × 2 = 144 km."},
      {u:"ÜNİTE 2 · Kuvvetin Etkisinde Hareket", q:"Duran bir cisme uygulanan kuvvetler dengelenmişse cisim ne yapar?", o:["Hızlanır","Durmaya devam eder","Yavaşça hareket eder","Yön değiştirir"], a:1,
       w:"Bileşke kuvvet sıfırsa cismin hareket durumu değişmez."},
      {u:"ÜNİTE 2 · Kuvvetin Etkisinde Hareket", q:"Kütlesi 3 kg olan cismin Dünya'daki ağırlığı kaç N'dur? (g = 10 N/kg)", o:["0,3","3","30","300"], a:2,
       w:"Ağırlık = 3 × 10 = 30 N."}
    ],
    tur:[
      {u:"KONU 1 · Sözcükte Anlam", q:"\"Dağın eteğinde kamp kurduk.\" cümlesinde \"etek\" hangi anlamdadır?", o:["Gerçek anlam","Yan anlam","Mecaz anlam","Terim anlam"], a:1,
       w:"Giysinin alt kısmına benzetilerek dağın alt bölümüne de etek denmiş — yan anlam."},
      {u:"KONU 1 · Sözcükte Anlam", q:"\"Tatlı bir dille konuştu.\" cümlesinde \"tatlı\" hangi anlamdadır?", o:["Gerçek anlam","Yan anlam","Mecaz anlam","Terim anlam"], a:2,
       w:"Tat anlamından uzaklaşıp \"hoş, yumuşak\" anlamı kazanmıştır."},
      {u:"KONU 1 · Sözcükte Anlam", q:"Aşağıdakilerden hangisi somut isimdir?", o:["Özlem","Korku","Masa","Akıl"], a:2,
       w:"Masa duyu organlarıyla algılanabilir, somuttur."},
      {u:"KONU 1 · Sözcükte Anlam", q:"\"Gül\" sözcüğü hangi cümlede fiil olarak kullanılmıştır?", o:["Bahçede gül açmış.","Bu kadar çok gülme.","Gül kokusu geliyor.","Gül dalı kırılmış."], a:1,
       w:"\"Gülme\" eylemi bildirir; diğerlerinde çiçek anlamındadır (eş sesli)."},
      {u:"KONU 1 · Sözcükte Anlam", q:"\"Cömert\" sözcüğünün zıt anlamlısı hangisidir?", o:["Eli açık","Cimri","Kibar","Yardımsever"], a:1,
       w:"Cömert ile cimri karşıt anlamlıdır."},
      {u:"KONU 2 · Deyimler, Atasözleri ve Söz Sanatları", q:"\"Sakla samanı, gelir zamanı.\" ifadesi ne anlatır?", o:["Tutumlu olmayı","Çok çalışmayı","Sabırlı olmayı","Dürüst olmayı"], a:0,
       w:"İşe yaramaz görünen şeyin bir gün gerekebileceğini, tutumlu olmayı öğütler."},
      {u:"KONU 2 · Deyimler, Atasözleri ve Söz Sanatları", q:"\"Kulak kesilmek\" deyiminin anlamı nedir?", o:["İşitme kaybı yaşamak","Dikkatle dinlemek","Söz dinlememek","Sessiz kalmak"], a:1,
       w:"Bütün dikkatini vererek dinlemek anlamındadır."},
      {u:"KONU 2 · Deyimler, Atasözleri ve Söz Sanatları", q:"\"Yıldızlar bize göz kırpıyordu.\" cümlesinde hangi söz sanatı vardır?", o:["Benzetme","Abartma","Kişileştirme","Konuşturma"], a:2,
       w:"Yıldızlara insana ait \"göz kırpmak\" eylemi verilmiştir."},
      {u:"KONU 2 · Deyimler, Atasözleri ve Söz Sanatları", q:"\"Bir ah çekti, dağlar yerinden oynadı.\" cümlesindeki söz sanatı hangisidir?", o:["Benzetme","Abartma","Konuşturma","Karşıtlık"], a:1,
       w:"Olayı gerçekte mümkün olmayacak kadar büyütmek abartmadır."},
      {u:"KONU 2 · Deyimler, Atasözleri ve Söz Sanatları", q:"Aşağıdakilerden hangisi deyimdir?", o:["Ağaç yaşken eğilir.","Göze girmek","Damlaya damlaya göl olur.","Sakla samanı, gelir zamanı."], a:1,
       w:"\"Göze girmek\" öğüt vermez, bir durumu anlatır — deyimdir. Diğerleri atasözüdür."}
    ],
    sos:[
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Bir kişinin aynı anda hem öğrenci hem kardeş olması neyi gösterir?", o:["Rollerin çakıştığını","Aynı anda birden çok sosyal rolü olduğunu","Rolün değişmediğini","Rolün mesleğe bağlı olduğunu"], a:1,
       w:"Bir kişi aynı anda birden çok sosyal role sahip olabilir."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Toplumsal bir soruna çözüm önerirken ilk yapılması gereken nedir?", o:["Sorunu tanımlamak","Para toplamak","Yetkililere şikâyet etmek","Sorunu görmezden gelmek"], a:0,
       w:"Önce sorun açıkça tanımlanır, sonra nedenleri bulunur ve uygulanabilir öneri getirilir."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Çocuk Hakları Sözleşmesi'ne Türkiye taraf mıdır?", o:["Hayır","Evet","Kısmen","Bilinmiyor"], a:1,
       w:"Türkiye sözleşmeye taraf olan ülkeler arasındadır."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"El sanatları ve mutfak kültürü hangi başlığa girer?", o:["Doğal kaynaklar","Kültürel değerler","Ekonomik faaliyetler","Yönetim biçimleri"], a:1,
       w:"Bunlar toplumun ortak kültürel mirasının parçasıdır."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"\"Bir kişinin hakkının bittiği yer, başkasının hakkının başladığı yerdir\" ifadesi neyi anlatır?", o:["Hakların sınırsız olduğunu","Hak ile sorumluluğun birlikte olduğunu","Sorumluluğun gereksiz olduğunu","Hakların yalnızca yetişkinlere ait olduğunu"], a:1,
       w:"Her hakkın yanında başkasının hakkını gözetme sorumluluğu vardır."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Dünyanın en büyük okyanusu hangisidir?", o:["Atlas Okyanusu","Hint Okyanusu","Büyük (Pasifik) Okyanus","Kuzey Buz Denizi"], a:2,
       w:"Büyük Okyanus (Pasifik) en geniş okyanustur."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Türkiye hangi enlemler arasında yer alır?", o:["26°–45° kuzey","36°–42° kuzey","36°–42° güney","0°–23° kuzey"], a:1,
       w:"36°–42° kuzey enlemleri, 26°–45° doğu boylamları arasındadır."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Yazları sıcak kurak, kışları soğuk ve kar yağışlı geçen iklim hangisidir?", o:["Akdeniz iklimi","Karadeniz iklimi","Karasal iklim","Muson iklimi"], a:2,
       w:"Karasal iklim iç bölgelerde görülür; kışları soğuk ve karlıdır."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Türkçenin ve Türk kültürünün yurt dışında tanıtılmasıyla görevli kurum hangisidir?", o:["TİKA","TÜRKSOY","Yunus Emre Enstitüsü","TSE"], a:2,
       w:"Yunus Emre Enstitüsü Türkçe öğretimi ve kültür tanıtımı yapar."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Aşağıdakilerden hangisi doğal çevre unsurudur?", o:["Otoyol","Akarsu","Fabrika","Köprü"], a:1,
       w:"Akarsu insandan bağımsız oluşur; diğerleri beşerî çevre unsurudur."}
    ],
    din:[
      {u:"ÜNİTE 1 · Peygamber ve İlahi Kitap İnancı", q:"Hz. Musa'ya verilen kitap ve Hz. Davud'a verilen kitap sırasıyla hangileridir?", o:["Zebur – Tevrat","Tevrat – Zebur","İncil – Tevrat","Tevrat – İncil"], a:1,
       w:"Tevrat Hz. Musa'ya, Zebur Hz. Davud'a indirilmiştir."},
      {u:"ÜNİTE 1 · Peygamber ve İlahi Kitap İnancı", q:"\"Fetanet\" sıfatı ne anlama gelir?", o:["Doğru sözlü olmak","Akıllı ve anlayışlı olmak","Güvenilir olmak","Günahsız olmak"], a:1,
       w:"Fetanet, peygamberin akıllı ve anlayışlı olmasıdır."},
      {u:"ÜNİTE 1 · Peygamber ve İlahi Kitap İnancı", q:"Suhuf verilen peygamberlerden biri hangisidir?", o:["Hz. Musa","Hz. İbrahim","Hz. İsa","Hz. Muhammed"], a:1,
       w:"Suhuf Hz. Âdem, Hz. Şit, Hz. İdris ve Hz. İbrahim'e verilmiştir."},
      {u:"ÜNİTE 1 · Peygamber ve İlahi Kitap İnancı", q:"Peygamberler hangi özellikleriyle diğer insanlardan ayrılır?", o:["Ölümsüz olmalarıyla","Ahlakları ve görevleriyle","Yemeyip içmemeleriyle","Gaybı bilmeleriyle"], a:1,
       w:"Peygamberler de insandır; üstünlükleri ahlaklarından ve görevlerinden gelir."},
      {u:"ÜNİTE 1 · Peygamber ve İlahi Kitap İnancı", q:"Ulu'l-azm peygamberler kaç tanedir?", o:["Üç","Dört","Beş","Altı"], a:2,
       w:"Hz. Nuh, Hz. İbrahim, Hz. Musa, Hz. İsa ve Hz. Muhammed — beş tanedir."}
    ],
    ing:[
      {u:"TEMA 1 · Classroom Life", q:"____ open your books, please.", o:["You","To","—","Do"], a:2,
       w:"Emir cümlesi özne almaz: \"Open your books, please.\""},
      {u:"TEMA 1 · Classroom Life", q:"\"Makas\" sözcüğünün İngilizcesi hangisidir?", o:["glue","scissors","marker","dictionary"], a:1,
       w:"Scissors makas, glue yapıştırıcı, dictionary sözlüktür."},
      {u:"TEMA 1 · Classroom Life", q:"There ____ a board and three windows in the classroom.", o:["is","are","have","has"], a:0,
       w:"There is/are kendinden sonraki ilk isme uyar; \"a board\" tekildir."},
      {u:"TEMA 1 · Classroom Life", q:"Arkadaşından kalem ödünç isterken hangisi uygundur?", o:["Give me a pencil.","Can I borrow your pencil, please?","I want pencil.","You give pencil."], a:1,
       w:"Kibar rica için \"Can I borrow…, please?\" kullanılır."},
      {u:"TEMA 1 · Classroom Life", q:"Olumsuz yap: \"Close the window.\"", o:["Not close the window.","Don't close the window.","No close the window.","Doesn't close the window."], a:1,
       w:"Olumsuz emir \"Don't + yalın fiil\" ile kurulur."},
      {u:"TEMA 2 · School Life", q:"We have Music ____ Friday afternoon.", o:["in","at","on","to"], a:2,
       w:"Belirli bir günün bölümü söyleniyorsa \"on\" kullanılır: on Friday afternoon."},
      {u:"TEMA 2 · School Life", q:"\"Bilişim Teknolojileri\" dersinin kısaltması hangisidir?", o:["PE","IT","Art","SS"], a:1,
       w:"IT = Information Technologies. PE beden eğitimidir."},
      {u:"TEMA 2 · School Life", q:"The school year starts ____ September.", o:["at","on","in","by"], a:2,
       w:"Ay adlarından önce \"in\" kullanılır."},
      {u:"TEMA 2 · School Life", q:"I study ____ night.", o:["in","at","on","to"], a:1,
       w:"\"At night\" bir istisnadır; günün diğer bölümlerinde \"in\" kullanılır."},
      {u:"TEMA 2 · School Life", q:"\"Dönem\" anlamına gelen sözcük hangisidir?", o:["break","term","grade","rule"], a:1,
       w:"Term dönem, break teneffüs, grade not demektir."}
    ]
  };

  var H7 = {
    mat:[
      {u:"TEMA 1 · Sayılar ve Nicelikler (1)", q:"(−5/6) + (1/3) işleminin sonucu kaçtır?", o:["−1/2","−2/3","1/2","−4/3"], a:0,
       w:"Payda 6: −5/6 + 2/6 = −3/6 = −1/2."},
      {u:"TEMA 1 · Sayılar ve Nicelikler (1)", q:"|−4| · |−3| işleminin sonucu kaçtır?", o:["−12","−7","7","12"], a:3,
       w:"Mutlak değerler alınır: 4 · 3 = 12."},
      {u:"TEMA 1 · Sayılar ve Nicelikler (1)", q:"0,8̄ devirli ondalık sayısının kesir gösterimi hangisidir?", o:["8/10","8/9","8/99","4/5"], a:1,
       w:"Tek basamak devrediyorsa payda 9 olur: 8/9."},
      {u:"TEMA 1 · Sayılar ve Nicelikler (1)", q:"−0,6 ile −2/3 sayılarından hangisi büyüktür?", o:["−0,6","−2/3","Eşittirler","Karşılaştırılamaz"], a:0,
       w:"−2/3 ≈ −0,666. Sayı doğrusunda −0,6 daha sağdadır, yani daha büyüktür."},
      {u:"TEMA 1 · Sayılar ve Nicelikler (1)", q:"(2/5) · (−15/8) işleminin sonucu kaçtır?", o:["−3/4","3/4","−4/3","−30/13"], a:0,
       w:"(2·−15)/(5·8) = −30/40 = −3/4."},
      {u:"TEMA 2 · Sayılar ve Nicelikler (2)", q:"Bir ürün %40 indirimle 270 TL'ye satılıyorsa indirimden önceki fiyatı kaç TL'dir?", o:["378","432","450","480"], a:2,
       w:"x · 0,60 = 270 → x = 450 TL."},
      {u:"TEMA 2 · Sayılar ve Nicelikler (2)", q:"5 musluk bir havuzu 12 saatte dolduruyorsa, 6 musluk kaç saatte doldurur?", o:["10","10,5","14,4","15"], a:0,
       w:"Ters orantı: 5 × 12 = 6 × s → s = 10 saat."},
      {u:"TEMA 2 · Sayılar ve Nicelikler (2)", q:"Bir sınıfta 12 kız, 18 erkek vardır. Kızların tüm sınıfa oranı kaçtır?", o:["2/3","2/5","3/5","1/2"], a:1,
       w:"Toplam 30 öğrenci. 12/30 = 2/5."},
      {u:"TEMA 2 · Sayılar ve Nicelikler (2)", q:"Maliyeti 500 TL olan ürün %20 kârla satılıp sonra %10 indirim yapılırsa son fiyat kaç TL olur?", o:["520","540","550","560"], a:1,
       w:"500 × 1,20 = 600; 600 × 0,90 = 540 TL."},
      {u:"TEMA 2 · Sayılar ve Nicelikler (2)", q:"Aşağıdakilerden hangisi doğru orantılı iki çokluktur?", o:["İşçi sayısı – işi bitirme süresi","Hız – aynı yolu alma süresi","Alınan kumaş uzunluğu – ödenen para","Musluk sayısı – havuzu doldurma süresi"], a:2,
       w:"Kumaş arttıkça ödenen para da artar; bölümleri sabittir."}
    ],
    fen:[
      {u:"ÜNİTE 1 · Uzay Çağı", q:"Bir ışık yılı yaklaşık kaç kilometredir?", o:["9,5 milyon km","9,5 milyar km","9,5 trilyon km","9,5 katrilyon km"], a:2,
       w:"Işığın bir yılda aldığı yol yaklaşık 9,5 trilyon kilometredir."},
      {u:"ÜNİTE 1 · Uzay Çağı", q:"Atmosferde yanmadan yere ulaşan gök taşına ne ad verilir?", o:["Meteor","Meteorit","Asteroit","Komet"], a:1,
       w:"Yanarken meteor, yere düşen parçaya meteorit denir."},
      {u:"ÜNİTE 1 · Uzay Çağı", q:"Aşağıdakilerden hangisi uzay teknolojisinin yan ürünü DEĞİLDİR?", o:["Uydu haberleşmesi","Hava durumu tahmini","GPS","Rüzgâr türbini"], a:3,
       w:"Rüzgâr türbini uzay çalışmalarının ürünü değildir."},
      {u:"ÜNİTE 1 · Uzay Çağı", q:"Yıldızlar neden ışık üretir?", o:["Güneş'ten aldıkları için","Kendi enerjilerini ürettikleri için","Yansıttıkları için","Atmosferleri olduğu için"], a:1,
       w:"Yıldızlar kendi enerjisini üretir; bu yüzden ışık ve ısı yayarlar."},
      {u:"ÜNİTE 1 · Uzay Çağı", q:"Uzay sondası hangi amaçla kullanılır?", o:["Dünya'dan gözlem yapmak","Gök cismine gidip yerinde ölçüm yapmak","Radyo dalgası yaymak","Hava tahmini yapmak"], a:1,
       w:"Sonda hedef gök cismine gider; teleskop ise uzaktan gözler."},
      {u:"ÜNİTE 2 · Kuvvet ve Enerjiyi Keşfedelim", q:"30 N'luk kuvvetle cisim kuvvet yönünde 5 m taşınırsa yapılan iş kaç joule'dür?", o:["6","35","150","1500"], a:2,
       w:"İş = 30 × 5 = 150 J."},
      {u:"ÜNİTE 2 · Kuvvet ve Enerjiyi Keşfedelim", q:"Bir cismin kinetik enerjisi hangi durumda artar?", o:["Yüksekliği artarsa","Hızı artarsa","Rengi değişirse","Hacmi azalırsa"], a:1,
       w:"Kinetik enerji cismin kütlesine ve hızına bağlıdır."},
      {u:"ÜNİTE 2 · Kuvvet ve Enerjiyi Keşfedelim", q:"Ağırlığın birimi ve ölçme aracı hangisidir?", o:["Kilogram – terazi","Newton – dinamometre","Joule – dinamometre","Newton – terazi"], a:1,
       w:"Ağırlık bir kuvvettir; newton ile ifade edilir ve dinamometre ile ölçülür."},
      {u:"ÜNİTE 2 · Kuvvet ve Enerjiyi Keşfedelim", q:"İş yapılabilmesi için hangisi gerekmez?", o:["Kuvvet uygulanması","Cismin yol alması","Yolun kuvvet doğrultusunda olması","Cismin renginin değişmesi"], a:3,
       w:"İş için kuvvet, yol ve bu ikisinin aynı doğrultuda olması gerekir."},
      {u:"ÜNİTE 2 · Kuvvet ve Enerjiyi Keşfedelim", q:"Yayı sıkıştırılmış bir oyuncak bırakıldığında hangi dönüşüm olur?", o:["Kinetik → potansiyel","Potansiyel → kinetik","Isı → kinetik","Elektrik → ısı"], a:1,
       w:"Sıkışmış yayda depolanan esneklik potansiyel enerjisi, bırakılınca harekete (kinetik enerjiye) dönüşür."}
    ],
    tur:[
      {u:"TEMA 1 · Hayat Boyu Gelişim", q:"\"Yarın erken kalkacağım.\" cümlesindeki kip hangisidir?", o:["Geniş zaman","Gelecek zaman","İstek","Gereklilik"], a:1,
       w:"-acak / -ecek eki gelecek zaman kipidir."},
      {u:"TEMA 1 · Hayat Boyu Gelişim", q:"\"Bu kitabı okusam iyi olur.\" cümlesindeki kip hangisidir?", o:["Şart","İstek","Gereklilik","Emir"], a:0,
       w:"-sa / -se eki şart (dilek-koşul) kipidir."},
      {u:"TEMA 1 · Hayat Boyu Gelişim", q:"Hangi cümlede anlam kayması vardır?", o:["Şu an ödev yapıyorum.","Dün sinemaya gittik.","Gelecek hafta İstanbul'a gidiyorum.","Her gün süt içerim."], a:2,
       w:"Şimdiki zaman eki kullanılmış ama \"gelecek hafta\" ile gelecek zaman anlatılıyor."},
      {u:"TEMA 1 · Hayat Boyu Gelişim", q:"\"Gelmişsin\" fiilinin kipi ve kişisi hangisidir?", o:["Duyulan geçmiş, 2. tekil","Görülen geçmiş, 2. tekil","Duyulan geçmiş, 3. tekil","Geniş zaman, 2. tekil"], a:0,
       w:"-miş duyulan geçmiş zaman, -sin 2. tekil kişi ekidir."},
      {u:"TEMA 1 · Hayat Boyu Gelişim", q:"Aşağıdakilerden hangisi haber kipidir?", o:["Gereklilik","İstek","Geniş zaman","Emir"], a:2,
       w:"Haber kipleri zaman bildirir: görülen/duyulan geçmiş, şimdiki, gelecek, geniş zaman."}
    ],
    sos:[
      {u:"ALAN 1 · Birlikte Yaşamak", q:"\"Geç kaldığında haber vermezsen endişeleniyorum.\" cümlesi hangi dile örnektir?", o:["Sen dili","Ben dili","Emir dili","Suçlayıcı dil"], a:1,
       w:"Davranış tarif edilmiş, konuşanın duygusu anlatılmış — ben dili."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Bir haberin güvenilirliğini artıran şey hangisidir?", o:["Çok paylaşılmış olması","Kaynağının belli ve güvenilir olması","Başlığının dikkat çekici olması","Resimli olması"], a:1,
       w:"Kaynağın kim olduğu, tarihi ve başka güvenilir kaynaklarda doğrulanması önemlidir."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Empati kurmak ne sağlar?", o:["Karşıdakine hak vermeyi","Karşıdakinin bakış açısını anlamayı","Tartışmayı kazanmayı","Konuyu değiştirmeyi"], a:1,
       w:"Empati, taraf olmadan karşıdakinin yerinden bakabilmektir."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"Basın özgürlüğü hangi durumda sınırlanır?", o:["Haber uzun olduğunda","Kişilerin özel hayatı ihlal edildiğinde","Haber çok okunduğunda","Fotoğraf kullanıldığında"], a:1,
       w:"Özel hayatın gizliliği ve kişilik hakları basın özgürlüğünün sınırıdır."},
      {u:"ALAN 1 · Birlikte Yaşamak", q:"\"Ben senin yüzünden geç kaldım.\" cümlesi hangi dile girer?", o:["Ben dili","Sen dili","Nesnel dil","Empatik dil"], a:1,
       w:"\"Ben\" ile başlasa da suçlama içerdiği için sen dilidir."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Nüfusun seyrek olduğu yerlerin ortak özelliği hangisidir?", o:["Ulaşımın kolay olması","Engebeli arazi ve sert iklim","Sanayinin gelişmiş olması","Kıyıda bulunması"], a:1,
       w:"Dağlık, engebeli ve sert iklimli alanlarda nüfus seyrektir."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Aşağıdakilerden hangisi beşerî faktördür?", o:["İklim","Yer şekilleri","Sanayi","Su kaynakları"], a:2,
       w:"Sanayi, ulaşım, tarım ve turizm beşerî faktörlerdir."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Bir ülkeden başka bir ülkeye yapılan göç hangi türdendir?", o:["İç göç","Dış göç","Mevsimlik göç","Kırsal göç"], a:1,
       w:"Ülke sınırları dışına yapılan göç dış göçtür."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Kırdan kente göçün kırsalda yol açtığı sonuç hangisidir?", o:["Nüfusun artması","Tarım iş gücünün azalması","Okulların çoğalması","Sanayinin gelişmesi"], a:1,
       w:"Genç nüfus kente gidince kırsalda çalışacak iş gücü azalır."},
      {u:"ALAN 2 · Evimiz Dünya", q:"Nüfus piramidinin tabanının daralması neyi gösterir?", o:["Doğum oranının azaldığını","Ölüm oranının azaldığını","Göç alındığını","Nüfusun gençleştiğini"], a:0,
       w:"Dar taban, doğum oranının düştüğünü ve nüfusun yaşlandığını gösterir."}
    ],
    din:[
      {u:"ÜNİTE 1 · Melek ve Ahiret İnancı", q:"Canlıların ruhunu almakla görevli melek hangisidir?", o:["Cebrail","Mikail","İsrafil","Azrail"], a:3,
       w:"Azrail ruhları almakla görevlidir."},
      {u:"ÜNİTE 1 · Melek ve Ahiret İnancı", q:"Melekler ne ile emredilmiştir?", o:["İsyan etmekle","Allah'a itaat etmekle","Uyumakla","Yemek yemekle"], a:1,
       w:"Melekler Allah'a isyan etmez, verilen görevi eksiksiz yerine getirir."},
      {u:"ÜNİTE 1 · Melek ve Ahiret İnancı", q:"Ahiret hayatında amellerin tartıldığı aşamaya ne ad verilir?", o:["Mahşer","Mizan","Berzah","Ba's"], a:1,
       w:"Mizan, amellerin tartılmasıdır."},
      {u:"ÜNİTE 1 · Melek ve Ahiret İnancı", q:"Kabir hayatına verilen ad hangisidir?", o:["Mahşer","Berzah","Mizan","Kıyamet"], a:1,
       w:"Ölümle yeniden diriliş arasındaki döneme berzah denir."},
      {u:"ÜNİTE 1 · Melek ve Ahiret İnancı", q:"Vahiy getirmekle görevli melek hangisidir?", o:["Azrail","İsrafil","Cebrail","Mikail"], a:2,
       w:"Cebrail peygamberlere vahiy getirmekle görevlidir."}
    ],
    ing:[
      {u:"TEMA 1 · School Life & Education", q:"I ____ study tonight. I have an exam tomorrow.", o:["mustn't","must","don't have to","couldn't"], a:1,
       w:"Konuşanın kendi koyduğu güçlü zorunluluk için \"must\" kullanılır."},
      {u:"TEMA 1 · School Life & Education", q:"\"Devam, katılım\" anlamına gelen sözcük hangisidir?", o:["attendance","absence","achievement","assembly"], a:0,
       w:"Attendance devam/katılım, absence devamsızlıktır."},
      {u:"TEMA 1 · School Life & Education", q:"We ____ wear our uniforms on Saturdays. There is no school.", o:["must","have to","don't have to","mustn't"], a:2,
       w:"Gerekmediğini anlatmak için \"don't have to\" kullanılır."},
      {u:"TEMA 1 · School Life & Education", q:"\"Ders programı\" anlamına gelen sözcük hangisidir?", o:["term","timetable","grade","rule"], a:1,
       w:"Timetable ders programıdır."},
      {u:"TEMA 1 · School Life & Education", q:"How often do you have Maths lessons? sorusuna uygun cevap hangisidir?", o:["At school.","Five times a week.","With my friend.","In the morning."], a:1,
       w:"\"How often\" sıklık sorar; cevabı \"five times a week\" gibi olur."},
      {u:"TEMA 2 · Classroom Life & Learning", q:"____ you speak French when you were little?", o:["Can","Could","Will","Must"], a:1,
       w:"Geçmişteki yetenek için \"could\" kullanılır."},
      {u:"TEMA 2 · Classroom Life & Learning", q:"\"Ezberlemek\" anlamındaki fiil hangisidir?", o:["memorise","revise","practise","highlight"], a:0,
       w:"Memorise ezberlemek, revise tekrar etmektir."},
      {u:"TEMA 2 · Classroom Life & Learning", q:"\"Sunum\" anlamına gelen sözcük hangisidir?", o:["project","presentation","deadline","group work"], a:1,
       w:"Presentation sunum, project ise projedir."},
      {u:"TEMA 2 · Classroom Life & Learning", q:"Hangisi kibar bir ricadır?", o:["Repeat that.","You repeat that.","Could you repeat that, please?","Must you repeat that?"], a:2,
       w:"\"Could you…, please?\" en kibar rica kalıbıdır."},
      {u:"TEMA 2 · Classroom Life & Learning", q:"Next year I ____ speak English very well.", o:["will can","can will","will be able to","am able will"], a:2,
       w:"\"Can\" gelecek zamanla kullanılamaz; \"will be able to\" gelir."}
    ]
  };
